#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
app_produit_statistics:
    path: /produit-statistics
    controller: App\Controller\ProduitController::produitStatistics
